#web的路径配置
#server:
#  port: 8080
#  servlet:
#    context-path: /fly

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fly?serverTimezone=GMT%2b8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

